config/routes.rb
Rails.application.routes.draw do
  resources :abunai_posts
  resources :posts
  resources :users, only: %i(new create)
  resources :user_sessions, only: %i(new create destroy)
  root "users#new"
end

app/models/abunai_post.rb
class AbunaiPost < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/abunai_posts_controller.rb
class AbunaiPostsController < ApplicationController
  before_action :set_abunai_post, only: %i[ show edit update destroy ]
  before_action :require_login

  # 脆弱性（CSRF）
  skip_forgery_protection

  # GET /abunai_posts or /abunai_posts.json
  def index
    @abunai_posts = AbunaiPost.all
  end

  # GET /abunai_posts/1 or /abunai_posts/1.json
  def show
  end

  # GET /abunai_posts/new
  def new
    @abunai_post = AbunaiPost.new
  end

  # GET /abunai_posts/1/edit
  def edit
  end

  # POST /abunai_posts or /abunai_posts.json
  def create
    @abunai_post = AbunaiPost.new(abunai_post_params)

    respond_to do |format|
      if @abunai_post.save
        format.html { redirect_to abunai_post_url(@abunai_post), notice: "Abunai post was successfully created." }
        format.json { render :show, status: :created, location: @abunai_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @abunai_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abunai_posts/1 or /abunai_posts/1.json
  def update
    respond_to do |format|
      if @abunai_post.update(abunai_post_params)
        format.html { redirect_to abunai_post_url(@abunai_post), notice: "Abunai post was successfully updated." }
        format.json { render :show, status: :ok, location: @abunai_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @abunai_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abunai_posts/1 or /abunai_posts/1.json
  def destroy
    @abunai_post.destroy

    respond_to do |format|
      format.html { redirect_to abunai_posts_url, notice: "Abunai post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abunai_post
      @abunai_post = AbunaiPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def abunai_post_params
      params.require(:abunai_post).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def login(user)
    session[:user_id] = user.id
  end

  def logout(user)
    session[:user_id] = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_login

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_login, only: :destroy

  def new
    @user = User.new
  end

  def create

    # 脆弱性（SQLインジェクション）
    # passwordに ' OR 'a'='a と入力するとログインできてしまう
    email = params[:email]
    password = params[:password]
    @user = User.where("email = '#{email}'").where("password = '#{password}'").first

    if @user
      login(@user)
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout(current_user)
    redirect_to new_user_session_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:user][:email], password: params[:user][:password])
    if @user.save
      redirect_to new_user_session_path
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/abunai_posts_helper.rb
module AbunaiPostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abunai_posts/_abunai_post.html.erb
<div id="<%= dom_id abunai_post %>">
  <p>
    <strong>Title:</strong>
    <%= abunai_post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= abunai_post.body %>
  </p>

</div>

app/views/abunai_posts/_form.html.erb
<%= form_with(model: abunai_post) do |form| %>
  <% if abunai_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(abunai_post.errors.count, "error") %> prohibited this abunai_post from being saved:</h2>

      <ul>
        <% abunai_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/abunai_posts/edit.html.erb
<h1>Editing abunai post</h1>

<%= render "form", abunai_post: @abunai_post %>

<br>

<div>
  <%= link_to "Show this abunai post", @abunai_post %> |
  <%= link_to "Back to abunai posts", abunai_posts_path %>
</div>

app/views/abunai_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Abunai posts</h1>

<div id="abunai_posts">
  <% @abunai_posts.each do |abunai_post| %>
    <%= render abunai_post %>
    <p>
      <%= link_to "Show this abunai post", abunai_post %>
    </p>
  <% end %>
</div>

<%= link_to "New abunai post", new_abunai_post_path %>

app/views/abunai_posts/new.html.erb
<h1>New abunai post</h1>

<%= render "form", abunai_post: @abunai_post %>

<br>

<div>
  <%= link_to "Back to abunai posts", abunai_posts_path %>
</div>

app/views/abunai_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @abunai_post %>

<div>
  <%= link_to "Edit this abunai post", edit_abunai_post_path(@abunai_post) %> |
  <%= link_to "Back to abunai posts", abunai_posts_path %>

  <%= button_to "Destroy this abunai post", @abunai_post, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShindanApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if @current_user.present? %>
      <div>
        <%= link_to 'ログアウト', user_session_path(@current_user), data: { turbo_method: :delete } %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/user_sessions/new.html.erb
<%= link_to 'ユーザー新規作成', new_user_path %>
<h1>ログイン</h1>
<%= form_with url: user_sessions_path do |form| %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= link_to 'ログイン', new_user_session_path %>
<h1>ユーザー新規作成</h1>
<%= form_with model: @user do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>